
package com.wondertek.baiying.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloServiceImpl", targetNamespace = "http://webservice.baiying.wondertek.com/", wsdlLocation = "http://127.0.0.1/hello?wsdl")
public class HelloServiceImpl
    extends Service
{

    private final static URL HELLOSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException HELLOSERVICEIMPL_EXCEPTION;
    private final static QName HELLOSERVICEIMPL_QNAME = new QName("http://webservice.baiying.wondertek.com/", "HelloServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSERVICEIMPL_WSDL_LOCATION = url;
        HELLOSERVICEIMPL_EXCEPTION = e;
    }

    public HelloServiceImpl() {
        super(__getWsdlLocation(), HELLOSERVICEIMPL_QNAME);
    }

    public HelloServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERVICEIMPL_QNAME, features);
    }

    public HelloServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERVICEIMPL_QNAME);
    }

    public HelloServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERVICEIMPL_QNAME, features);
    }

    public HelloServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloService getHelloServiceImplPort() {
        return super.getPort(new QName("http://webservice.baiying.wondertek.com/", "HelloServiceImplPort"), HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public HelloService getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.baiying.wondertek.com/", "HelloServiceImplPort"), HelloService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERVICEIMPL_EXCEPTION!= null) {
            throw HELLOSERVICEIMPL_EXCEPTION;
        }
        return HELLOSERVICEIMPL_WSDL_LOCATION;
    }

}
